dias = int (input("Digite a quantidade de dias:")) 
horas = int (input("Digite a quantidade de horas:"))
segundos = int (input("Digite a quantidade de segundos:")) 
minutos = int (input("Digite a quantidade de minutos:")) 
segundostotais = segundos+(minutos*60)+(horas*60*60)+(dias*24*60*60)
print (segundostotais)